/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/schools`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/approvals`; params?: Router.UnknownInputParams; } | { pathname: `/admin/countries`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/manager/users`; params?: Router.UnknownInputParams; } | { pathname: `/admin/country/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/admin/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/manager/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/scenario/[schoolId]/[scenarioId]`, params: Router.UnknownInputParams & { schoolId: string | number;scenarioId: string | number; } } | { pathname: `/school/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/schools`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/approvals`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/countries`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/users`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/users`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/country/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/admin/user/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/manager/user/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/scenario/[schoolId]/[scenarioId]`, params: Router.UnknownOutputParams & { schoolId: string;scenarioId: string; } } | { pathname: `/school/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/schools${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/approvals${`?${string}` | `#${string}` | ''}` | `/admin/countries${`?${string}` | `#${string}` | ''}` | `/admin/users${`?${string}` | `#${string}` | ''}` | `/manager/users${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/schools`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/approvals`; params?: Router.UnknownInputParams; } | { pathname: `/admin/countries`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/manager/users`; params?: Router.UnknownInputParams; } | `/admin/country/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/admin/user/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/manager/user/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/scenario/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/school/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/admin/country/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/admin/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/manager/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/scenario/[schoolId]/[scenarioId]`, params: Router.UnknownInputParams & { schoolId: string | number;scenarioId: string | number; } } | { pathname: `/school/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
